import { format, parseISO } from 'date-fns';
import { Card, CardHeader, LoadingSpinner, ErrorMessage } from '@/components/ui';
import { useInsights } from '@/hooks/useInsights';
import type { Insight, InsightType } from '@/types/insight.types';
import styles from './AiInsightsWidget.module.css';

const INSIGHT_META: Record<InsightType, { icon: string; label: string; colorVar: string }> = {
  SPENDING_PATTERN: { icon: '📈', label: 'Spending Pattern', colorVar: '--color-primary' },
  BUDGET_WARNING: { icon: '⚠️', label: 'Budget Warning', colorVar: '--color-expense' },
  SAVING_OPPORTUNITY: { icon: '💡', label: 'Saving Opportunity', colorVar: '--color-income' },
  ANOMALY: { icon: '🔍', label: 'Anomaly Detected', colorVar: '--color-transfer' },
  MONTHLY_SUMMARY: { icon: '📋', label: 'Monthly Summary', colorVar: '--color-primary' },
};

const InsightCard = ({ insight }: { insight: Insight }) => {
  const meta = INSIGHT_META[insight.type];
  const date = format(parseISO(insight.generatedAt), 'MMM d');

  return (
    <div className={styles.insight}>
      <div className={styles.insight__header}>
        <span className={styles.insight__icon} aria-hidden="true">{meta.icon}</span>
        <div className={styles.insight__meta}>
          <span className={styles.insight__type} style={{ color: `var(${meta.colorVar})` }}>
            {meta.label}
          </span>
          <span className={styles.insight__date}>{date}</span>
        </div>
      </div>
      <p className={styles.insight__content}>{insight.content}</p>
    </div>
  );
};

export const AiInsightsWidget = () => {
  const { data, isLoading, isError, refetch } = useInsights(5);

  if (isLoading) return <Card><LoadingSpinner /></Card>;
  if (isError) return <Card><ErrorMessage onRetry={() => void refetch()} /></Card>;

  const insights = data ?? [];

  return (
    <Card>
      <CardHeader
        title="AI Insights"
        subtitle="Generated by AI based on your spending patterns"
      />
      {insights.length === 0 ? (
        <div className={styles.empty}>
          <span className={styles.empty__icon}>🤖</span>
          <p className={styles.empty__text}>
            No insights yet. AI will analyze your spending once you have enough transactions.
          </p>
        </div>
      ) : (
        <div className={styles.list}>
          {insights.map((insight) => (
            <InsightCard key={insight.id} insight={insight} />
          ))}
        </div>
      )}
    </Card>
  );
};
