export const ErrorCode = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Import
  INVALID_CSV: 'INVALID_CSV',
  EMPTY_CSV: 'EMPTY_CSV',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  IMPORT_JOB_NOT_FOUND: 'IMPORT_JOB_NOT_FOUND',

  // Account
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
